#!/bin/bash

b=$(xrandr --current --verbose | grep -m 1 Brightness | awk '{print $2}')
b=${b#0.}                       # 0.30 --> 30
[[ $b == "1.0" ]] && b="100"

b=$((b $1))

[[ $b -lt 10 ]] && b=10
[[ $b -gt 100 ]] && b=100

if [[ $b -eq 100 ]]; then
	b=1.0
else
	b=0.$b
fi

outputs=$(xrandr --current | awk '$2 == "connected" {print $1}')
for o in $outputs; do
    xrandr --output $o --brightness $b
done 

